### ISSUE TITLE
Redstone Wall Torch Model Shift between On/Off

### ISSUE THREAD

**Issue by LetsTryThisAgain** [Faithful3D/1.16#23] opened 2020-07-12 00:48 UTC
**Faithful 3D - 1.16 & 1.16.1 - R1)**

**Describe the bug**
The redstone wall torch model, when changing state (on off), shifts forwards/backwards a noticeable amount

**To Reproduce**
1. Place redstone torch on wall
2. Using a debug stick - toggle the torch on/off
3. Notice how the unlit redstone torch moves into the wall.

**Expected behavior**
The redstone wall torch model should remain stationary when on or off.

**Screenshots**
![2020-07-11_20 37 28](https://user-images.githubusercontent.com/67689396/87236359-74d80600-c3b6-11ea-89a6-226e120b437a.png)
![2020-07-11_20 37 30](https://user-images.githubusercontent.com/67689396/87236360-75709c80-c3b6-11ea-9553-88a5fdeaeacd.png)

Direct comparison:

Redline = Off Torch Border

Yellow Line = On Torch Border
![2020-07-11_20 37 28](https://user-images.githubusercontent.com/67689396/87236412-6807e200-c3b7-11ea-8f50-20a72a6c0c34.png)

**Additional context**
This bug was first reported/resolved in issue #19 

NOTE: This difference it noticeable in game - still images (above) make it much less apparent.

**Comment by Juknum** [comment] 2020-07-12 01:37
duplicate of #19

**Closed by Juknum** 2020-07-12 01:37 UTC
Labels: block, bug

**Comment by LetsTryThisAgain** [comment] 2020-07-16 12:12
Hey Juknum,
Yes #19 was the first to note this. This bug report is saying that, it still isn't fixed. It's closer but not exact. Hopefully you'll examine it!

**Comment by Juknum** [comment] 2020-07-16 20:36
Oops sorry I missed understood
